name: GitHub Actions Draft
on: [push]
jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Archive code
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'api-v00.zip'
          exclusions: '*.git* /tests/*'
      - name: Unzip to view zip file
        run: unzip aaaa-api-v00.zip -d ./res; ls -la ./res
      - name: Get release asset
        run: |
          mkdir ./output
          gh release download --repo YoshihikoFuruhashi/hello_poetry_build v0.1 -D ./output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files in the repository
        run: |
          ls -l ${{ github.workspace }}
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            api-v00.zip
            ./output
#uses: thedoctor0/zip-release@master
